/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Reservae API
 * API para gerenciamento de espaços, disponibilidades e reservas.
 * OpenAPI spec version: v1
 */
import type {
  BookingDto,
  BookingDtoPagedResponseDto,
  CreateBookingAutoDto,
  CreateBookingDto,
  GetApiBookingsMineParams,
  GetApiBookingsSpaceSpaceIdParams,
  UpdateBookingDto
} from '../models';


export const getGetApiBookingsMineUrl = (params?: GetApiBookingsMineParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5144"}/api/bookings/mine?${stringifiedParams}` : `${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5144"}/api/bookings/mine`
}

export const getApiBookingsMine = async (params?: GetApiBookingsMineParams, options?: RequestInit): Promise<BookingDtoPagedResponseDto> => {

  const res = await fetch(getGetApiBookingsMineUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {

    const err: globalThis.Error & {info?: any, status?: number} = new globalThis.Error();
    const data  = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: BookingDtoPagedResponseDto = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  return data
}


export const getGetApiBookingsSpaceSpaceIdUrl = (spaceId: number,
    params?: GetApiBookingsSpaceSpaceIdParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5144"}/api/bookings/space/${spaceId}?${stringifiedParams}` : `${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5144"}/api/bookings/space/${spaceId}`
}

export const getApiBookingsSpaceSpaceId = async (spaceId: number,
    params?: GetApiBookingsSpaceSpaceIdParams, options?: RequestInit): Promise<BookingDtoPagedResponseDto> => {

  const res = await fetch(getGetApiBookingsSpaceSpaceIdUrl(spaceId,params),
  {
    ...options,
    method: 'GET'


  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {

    const err: globalThis.Error & {info?: any, status?: number} = new globalThis.Error();
    const data  = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: BookingDtoPagedResponseDto = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  return data
}


export const getGetApiBookingsIdUrl = (id: number,) => {




  return `${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5144"}/api/bookings/${id}`
}

export const getApiBookingsId = async (id: number, options?: RequestInit): Promise<BookingDto> => {

  const res = await fetch(getGetApiBookingsIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {

    const err: globalThis.Error & {info?: any, status?: number} = new globalThis.Error();
    const data  = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: BookingDto = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  return data
}


export const getPutApiBookingsIdUrl = (id: number,) => {




  return `${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5144"}/api/bookings/${id}`
}

export const putApiBookingsId = async (id: number,
    updateBookingDto?: UpdateBookingDto, options?: RequestInit): Promise<BookingDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getPutApiBookingsIdUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateBookingDto)
  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {

    const err: globalThis.Error & {info?: any, status?: number} = new globalThis.Error();
    const data  = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: BookingDto = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  return data
}


export const getDeleteApiBookingsIdUrl = (id: number,) => {




  return `${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5144"}/api/bookings/${id}`
}

export const deleteApiBookingsId = async (id: number, options?: RequestInit): Promise<void> => {

  const res = await fetch(getDeleteApiBookingsIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {

    const err: globalThis.Error & {info?: any, status?: number} = new globalThis.Error();
    const data  = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: void = body ? JSON.parse(body) : undefined
  return data
}


export const getPostApiBookingsCreateManualUrl = () => {




  return `${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5144"}/api/bookings/create-manual`
}

export const postApiBookingsCreateManual = async (createBookingDto?: CreateBookingDto, options?: RequestInit): Promise<BookingDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getPostApiBookingsCreateManualUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createBookingDto)
  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {

    const err: globalThis.Error & {info?: any, status?: number} = new globalThis.Error();
    const data  = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: BookingDto = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  return data
}


export const getPostApiBookingsCreateAutoUrl = () => {




  return `${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5144"}/api/bookings/create-auto`
}

export const postApiBookingsCreateAuto = async (createBookingAutoDto?: CreateBookingAutoDto, options?: RequestInit): Promise<BookingDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getPostApiBookingsCreateAutoUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createBookingAutoDto)
  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {

    const err: globalThis.Error & {info?: any, status?: number} = new globalThis.Error();
    const data  = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: BookingDto = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  return data
}


