/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Reservae API
 * API para gerenciamento de espaços, disponibilidades e reservas.
 * OpenAPI spec version: v1
 */
import type {
  AvailabilityRuleDto,
  AvailabilityRuleDtoPagedResponseDto,
  CreateAvailabilityRuleDTO,
  GetApiAvailabilityRuleParams,
  UpdateAvailabilityRuleDTO
} from '../models';


export const getGetApiAvailabilityRuleUrl = (params?: GetApiAvailabilityRuleParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5144"}/api/availability-rule?${stringifiedParams}` : `${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5144"}/api/availability-rule`
}

export const getApiAvailabilityRule = async (params?: GetApiAvailabilityRuleParams, options?: RequestInit): Promise<AvailabilityRuleDtoPagedResponseDto> => {

  const res = await fetch(getGetApiAvailabilityRuleUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {

    const err: globalThis.Error & {info?: any, status?: number} = new globalThis.Error();
    const data  = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: AvailabilityRuleDtoPagedResponseDto = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  return data
}


export const getPostApiAvailabilityRuleUrl = () => {




  return `${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5144"}/api/availability-rule`
}

export const postApiAvailabilityRule = async (createAvailabilityRuleDTO?: CreateAvailabilityRuleDTO, options?: RequestInit): Promise<AvailabilityRuleDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getPostApiAvailabilityRuleUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createAvailabilityRuleDTO)
  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {

    const err: globalThis.Error & {info?: any, status?: number} = new globalThis.Error();
    const data  = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: AvailabilityRuleDto = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  return data
}


export const getGetApiAvailabilityRuleIdUrl = (id: number,) => {




  return `${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5144"}/api/availability-rule/${id}`
}

export const getApiAvailabilityRuleId = async (id: number, options?: RequestInit): Promise<AvailabilityRuleDto> => {

  const res = await fetch(getGetApiAvailabilityRuleIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {

    const err: globalThis.Error & {info?: any, status?: number} = new globalThis.Error();
    const data  = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: AvailabilityRuleDto = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  return data
}


export const getPutApiAvailabilityRuleIdUrl = (id: number,) => {




  return `${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5144"}/api/availability-rule/${id}`
}

export const putApiAvailabilityRuleId = async (id: number,
    updateAvailabilityRuleDTO?: UpdateAvailabilityRuleDTO, options?: RequestInit): Promise<AvailabilityRuleDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getPutApiAvailabilityRuleIdUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateAvailabilityRuleDTO)
  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {

    const err: globalThis.Error & {info?: any, status?: number} = new globalThis.Error();
    const data  = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: AvailabilityRuleDto = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  return data
}


