@Reservae_HostAddress = https://localhost:7085
@accessToken = COLE_O_ACCESS_TOKEN_DO_LOGIN_AQUI
@ownerId = faf079b7-2389-44a2-833c-c08614d3b674

### Cadastro
POST {{Reservae_HostAddress}}/auth/register
Content-Type: application/json

{
  "email": "teste@example.com",
  "password": "Teste123!"
}

### Login
POST {{Reservae_HostAddress}}/auth/login?useCookies=false
Content-Type: application/json

{
  "email": "teste@example.com",
  "password": "Teste123!"
}

### Usuario autenticado
GET {{Reservae_HostAddress}}/auth/me
Authorization: Bearer {{accessToken}}

### Criar espaco com categoria e preco opcionais
POST {{Reservae_HostAddress}}/api/spaces
Content-Type: application/json
//Authorization: Bearer {{accessToken}}

{
  "ownerId": "{{ownerId}}",
  "address": "Rua das Flores, 100",
  "title": "Espaco Aurora",
  "description": "Espaco criado para testar o endpoint",
  "coverImagePath": "/images/espaco-aurora.jpg",
  "category": 5,
  "pricePerSpot": 100.00
}

### Criar espaco usando os valores padrao opcionais
POST {{Reservae_HostAddress}}/api/spaces
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "ownerId": "{{ownerId}}",
  "address": "Rua das Flores, 200",
  "title": "Espaco sem preco customizado",
  "description": "Categoria e preco nao foram enviados",
  "coverImagePath": "/images/espaco-padrao.jpg"
}

### Listar espacos
GET {{Reservae_HostAddress}}/api/spaces?page=1&pageSize=10

###
