@Reservae_HostAddress = https://localhost:7085
@accessToken = COLE_O_ACCESS_TOKEN_DO_LOGIN_AQUI
@ownerId = faf079b7-2389-44a2-833c-c08614d3b674

### Cadastro
POST {{Reservae_HostAddress}}/auth/register
Content-Type: application/json

{
  "email": "teste@example.com",
  "password": "Teste123!"
}

### Login
POST {{Reservae_HostAddress}}/auth/login?useCookies=false
Content-Type: application/json

{
  "email": "teste@example.com",
  "password": "Teste123!"
}

### Usuario autenticado
GET {{Reservae_HostAddress}}/auth/me
Authorization: Bearer {{accessToken}}

### Criar espaco com categoria e preco opcionais
POST {{Reservae_HostAddress}}/api/spaces
Content-Type: application/json
//Authorization: Bearer {{accessToken}}

{
  "ownerId": "{{ownerId}}",
  "address": "Rua das Flores, 100",
  "title": "Espaco Aurora",
  "description": "Espaco criado para testar o endpoint",
  "coverImagePath": "/images/espaco-aurora.jpg",
  "category": 5,
  "pricePerSpot": 100.00
}

### Criar espaco usando os valores padrao opcionais
POST {{Reservae_HostAddress}}/api/spaces
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "ownerId": "{{ownerId}}",
  "address": "Rua das Flores, 200",
  "title": "Espaco sem preco customizado",
  "description": "Categoria e preco nao foram enviados",
  "coverImagePath": "/images/espaco-padrao.jpg"
}

### Listar espacos
GET {{Reservae_HostAddress}}/api/spaces?page=1&pageSize=3

### PEgar 1 espaço
GET {{Reservae_HostAddress}}/api/spaces/4

### Atualizar Espaço

### Criar espaco usando os valores padrao opcionais
PUT {{Reservae_HostAddress}}/api/spaces/4
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "ownerId": "adfasfsa"
}


##Availability Rules


### Criar Regra
POST {{Reservae_HostAddress}}/api/availability-rule
Content-Type: application/json
//Authorization: Bearer {{accessToken}}

{
  "spaceId": 4,
  "dayOfTheWeek": 1,
  "startTime": "08:00:00",
  "endTime": "12:00:00",
  "validFrom": "2026-09-18T00:00:00Z",
  "validUntil": "2026-12-31T23:59:59Z",
  "customPricePerSpot": 75.00,
  "isActive": true,
  "capacity": 10
}

### Listar regras
GET {{Reservae_HostAddress}}/api/availability-rule?page=1&pageSize=3

### Pegar 1 regra
GET {{Reservae_HostAddress}}/api/availability-rule/1

### Atualizar Espaço

### Criar espaco usando os valores padrao opcionais
PUT {{Reservae_HostAddress}}/api/availability-rule/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "startTime": "11:00:00"
}
