/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Reservae API
 * API para gerenciamento de espaços, disponibilidades e reservas.
 * OpenAPI spec version: v1
 */
import type {
  AvailableSlotDto,
  CreateSpaceDto,
  GetApiSpacesParams,
  GetApiSpacesSearchParams,
  GetApiSpacesSpaceIdAvailabilityParams,
  SpaceDTO,
  SpaceDTOPagedResponseDto,
  UpdateSpaceDto
} from '../models';


export const getGetApiSpacesSearchUrl = (params: GetApiSpacesSearchParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5144"}/api/spaces/search?${stringifiedParams}` : `${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5144"}/api/spaces/search`
}

export const getApiSpacesSearch = async (params: GetApiSpacesSearchParams, options?: RequestInit): Promise<SpaceDTOPagedResponseDto> => {

  const res = await fetch(getGetApiSpacesSearchUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {

    const err: globalThis.Error & {info?: any, status?: number} = new globalThis.Error();
    const data  = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: SpaceDTOPagedResponseDto = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  return data
}


export const getGetApiSpacesUrl = (params?: GetApiSpacesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5144"}/api/spaces?${stringifiedParams}` : `${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5144"}/api/spaces`
}

export const getApiSpaces = async (params?: GetApiSpacesParams, options?: RequestInit): Promise<SpaceDTOPagedResponseDto> => {

  const res = await fetch(getGetApiSpacesUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {

    const err: globalThis.Error & {info?: any, status?: number} = new globalThis.Error();
    const data  = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: SpaceDTOPagedResponseDto = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  return data
}


export const getPostApiSpacesUrl = () => {




  return `${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5144"}/api/spaces`
}

export const postApiSpaces = async (createSpaceDto?: CreateSpaceDto, options?: RequestInit): Promise<SpaceDTO> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getPostApiSpacesUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createSpaceDto)
  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {

    const err: globalThis.Error & {info?: any, status?: number} = new globalThis.Error();
    const data  = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: SpaceDTO = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  return data
}


export const getGetApiSpacesIdUrl = (id: number,) => {




  return `${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5144"}/api/spaces/${id}`
}

export const getApiSpacesId = async (id: number, options?: RequestInit): Promise<SpaceDTO> => {

  const res = await fetch(getGetApiSpacesIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {

    const err: globalThis.Error & {info?: any, status?: number} = new globalThis.Error();
    const data  = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: SpaceDTO = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  return data
}


export const getPutApiSpacesIdUrl = (id: number,) => {




  return `${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5144"}/api/spaces/${id}`
}

export const putApiSpacesId = async (id: number,
    updateSpaceDto?: UpdateSpaceDto, options?: RequestInit): Promise<SpaceDTO> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getPutApiSpacesIdUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateSpaceDto)
  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {

    const err: globalThis.Error & {info?: any, status?: number} = new globalThis.Error();
    const data  = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: SpaceDTO = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  return data
}


export const getGetApiSpacesSpaceIdAvailabilityUrl = (spaceId: number,
    params?: GetApiSpacesSpaceIdAvailabilityParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5144"}/api/spaces/${spaceId}/availability?${stringifiedParams}` : `${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5144"}/api/spaces/${spaceId}/availability`
}

export const getApiSpacesSpaceIdAvailability = async (spaceId: number,
    params?: GetApiSpacesSpaceIdAvailabilityParams, options?: RequestInit): Promise<AvailableSlotDto[]> => {

  const res = await fetch(getGetApiSpacesSpaceIdAvailabilityUrl(spaceId,params),
  {
    ...options,
    method: 'GET'


  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {

    const err: globalThis.Error & {info?: any, status?: number} = new globalThis.Error();
    const data  = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: AvailableSlotDto[] = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  return data
}


