/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Reservae API
 * API para gerenciamento de espaços, disponibilidades e reservas.
 * OpenAPI spec version: v1
 */
import type {
  PostApiUploadsImagesBody,
  SpaceDTO
} from '../models';


export const getPostApiUploadsImagesUrl = () => {




  return `${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5144"}/api/uploads/images`
}

export const postApiUploadsImages = async (postApiUploadsImagesBody?: PostApiUploadsImagesBody, options?: RequestInit): Promise<SpaceDTO> => {
    const formData = new FormData();
if(postApiUploadsImagesBody?.spaceId !== undefined) {
 formData.append(`spaceId`, postApiUploadsImagesBody.spaceId.toString())
 }
if(postApiUploadsImagesBody?.file !== undefined) {
 formData.append(`file`, postApiUploadsImagesBody.file);
 }

  const res = await fetch(getPostApiUploadsImagesUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {

    const err: globalThis.Error & {info?: any, status?: number} = new globalThis.Error();
    const data  = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: SpaceDTO = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  return data
}


