/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Reservae API
 * API para gerenciamento de espaços, disponibilidades e reservas.
 * OpenAPI spec version: v1
 */
import type {
  BookableSlotDTO,
  BookableSlotDTOPagedResponseDto,
  CreateBookableSlotDTO,
  GetApiBookableSlotsParams,
  GetApiBookableSlotsSpaceSpaceIdStandaloneParams,
  UpdateBookableSlotDTO
} from '../models';


export const getGetApiBookableSlotsUrl = (params?: GetApiBookableSlotsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5144"}/api/bookable-slots?${stringifiedParams}` : `${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5144"}/api/bookable-slots`
}

export const getApiBookableSlots = async (params?: GetApiBookableSlotsParams, options?: RequestInit): Promise<BookableSlotDTOPagedResponseDto> => {

  const res = await fetch(getGetApiBookableSlotsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {

    const err: globalThis.Error & {info?: any, status?: number} = new globalThis.Error();
    const data  = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: BookableSlotDTOPagedResponseDto = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  return data
}


export const getPostApiBookableSlotsUrl = () => {




  return `${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5144"}/api/bookable-slots`
}

export const postApiBookableSlots = async (createBookableSlotDTO?: CreateBookableSlotDTO, options?: RequestInit): Promise<BookableSlotDTO> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getPostApiBookableSlotsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createBookableSlotDTO)
  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {

    const err: globalThis.Error & {info?: any, status?: number} = new globalThis.Error();
    const data  = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: BookableSlotDTO = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  return data
}


export const getGetApiBookableSlotsIdUrl = (id: number,) => {




  return `${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5144"}/api/bookable-slots/${id}`
}

export const getApiBookableSlotsId = async (id: number, options?: RequestInit): Promise<BookableSlotDTO> => {

  const res = await fetch(getGetApiBookableSlotsIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {

    const err: globalThis.Error & {info?: any, status?: number} = new globalThis.Error();
    const data  = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: BookableSlotDTO = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  return data
}


export const getPutApiBookableSlotsIdUrl = (id: number,) => {




  return `${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5144"}/api/bookable-slots/${id}`
}

export const putApiBookableSlotsId = async (id: number,
    updateBookableSlotDTO?: UpdateBookableSlotDTO, options?: RequestInit): Promise<BookableSlotDTO> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getPutApiBookableSlotsIdUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateBookableSlotDTO)
  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {

    const err: globalThis.Error & {info?: any, status?: number} = new globalThis.Error();
    const data  = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: BookableSlotDTO = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  return data
}


export const getDeleteApiBookableSlotsIdUrl = (id: number,) => {




  return `${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5144"}/api/bookable-slots/${id}`
}

export const deleteApiBookableSlotsId = async (id: number, options?: RequestInit): Promise<void> => {

  const res = await fetch(getDeleteApiBookableSlotsIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {

    const err: globalThis.Error & {info?: any, status?: number} = new globalThis.Error();
    const data  = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: void = body ? JSON.parse(body) : undefined
  return data
}


export const getGetApiBookableSlotsSpaceSpaceIdStandaloneUrl = (spaceId: number,
    params?: GetApiBookableSlotsSpaceSpaceIdStandaloneParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5144"}/api/bookable-slots/space/${spaceId}/standalone?${stringifiedParams}` : `${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5144"}/api/bookable-slots/space/${spaceId}/standalone`
}

export const getApiBookableSlotsSpaceSpaceIdStandalone = async (spaceId: number,
    params?: GetApiBookableSlotsSpaceSpaceIdStandaloneParams, options?: RequestInit): Promise<BookableSlotDTOPagedResponseDto> => {

  const res = await fetch(getGetApiBookableSlotsSpaceSpaceIdStandaloneUrl(spaceId,params),
  {
    ...options,
    method: 'GET'


  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {

    const err: globalThis.Error & {info?: any, status?: number} = new globalThis.Error();
    const data  = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: BookableSlotDTOPagedResponseDto = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  return data
}


