/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Reservae API
 * API para gerenciamento de espaços, disponibilidades e reservas.
 * OpenAPI spec version: v1
 */

export interface AccessTokenResponse {
  /** @nullable */
  readonly tokenType?: string | null;
  /** @nullable */
  accessToken: string | null;
  expiresIn: number;
  /** @nullable */
  refreshToken: string | null;
}
