/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Reservae API
 * API para gerenciamento de espaços, disponibilidades e reservas.
 * OpenAPI spec version: v1
 */
import type { AvailabilityRuleDto } from './availabilityRuleDto';

export interface AvailabilityRuleDtoPagedResponseDto {
  /** @nullable */
  items?: AvailabilityRuleDto[] | null;
  totalCount?: number;
}
