/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Reservae API
 * API para gerenciamento de espaços, disponibilidades e reservas.
 * OpenAPI spec version: v1
 */
import type { BookingStatusEnum } from './bookingStatusEnum';
import type { CategoryEnum } from './categoryEnum';

export interface BookingDto {
  id?: number;
  bookableSlotId?: number;
  /** @nullable */
  userBookedName: string | null;
  status?: BookingStatusEnum;
  quantity?: number;
  /** @nullable */
  spaceId?: number | null;
  /** @nullable */
  spaceTitle?: string | null;
  /** @nullable */
  spaceAddress?: string | null;
  spaceCategory?: CategoryEnum;
  /** @nullable */
  spaceCoverImagePath?: string | null;
  /** @nullable */
  startsAt?: string | null;
  /** @nullable */
  endsAt?: string | null;
}
