/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Reservae API
 * API para gerenciamento de espaços, disponibilidades e reservas.
 * OpenAPI spec version: v1
 */
import type { BookableSlotDTO } from './bookableSlotDTO';

export interface BookableSlotDTOPagedResponseDto {
  /** @nullable */
  items?: BookableSlotDTO[] | null;
  totalCount?: number;
}
