/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Reservae API
 * API para gerenciamento de espaços, disponibilidades e reservas.
 * OpenAPI spec version: v1
 */

export interface CreateBookingAutoDto {
  /**
     * @minimum 1
     * @maximum 2147483647
     * @nullable
     */
  bookableSlotId?: number | null;
  /**
     * @minimum 1
     * @maximum 2147483647
     * @nullable
     */
  availabilityRuleId?: number | null;
  /**
     * @minimum 1
     * @maximum 2147483647
     */
  spaceId?: number;
  startsAt?: string;
  endsAt?: string;
  /**
     * @minimum 1
     * @maximum 2147483647
     */
  quantity?: number;
}
