/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Reservae API
 * API para gerenciamento de espaços, disponibilidades e reservas.
 * OpenAPI spec version: v1
 */
import type { CategoryEnum } from './categoryEnum';

export interface CreateSpaceDto {
  /** @minLength 1 */
  ownerId: string;
  /**
     * @minLength 0
     * @maxLength 500
     */
  address: string;
  /**
     * @minLength 0
     * @maxLength 200
     */
  title: string;
  /**
     * @minLength 0
     * @maxLength 4000
     */
  description: string;
  category?: CategoryEnum;
  /**
     * @minimum 0
     * @maximum 1.7976931348623157e+308
     * @nullable
     */
  pricePerSpot?: number | null;
}
