/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Reservae API
 * API para gerenciamento de espaços, disponibilidades e reservas.
 * OpenAPI spec version: v1
 */
import type { DayOfTheWeekEnum } from './dayOfTheWeekEnum';

export type GetApiSpacesSpaceIdAvailabilityParams = {
fromDate?: string;
toDate?: string;
dayOfTheWeek?: DayOfTheWeekEnum;
};
