/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Reservae API
 * API para gerenciamento de espaços, disponibilidades e reservas.
 * OpenAPI spec version: v1
 */

/**
 * @nullable
 */
export type HttpValidationProblemDetailsErrors = {[key: string]: string[]} | null;
