/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Reservae API
 * API para gerenciamento de espaços, disponibilidades e reservas.
 * OpenAPI spec version: v1
 */

export type MapIdentityApiAuthConfirmEmailParams = {
userId: string;
code: string;
changedEmail?: string;
};
