/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Reservae API
 * API para gerenciamento de espaços, disponibilidades e reservas.
 * OpenAPI spec version: v1
 */

export type PostApiUploadsImagesBody = {
  /**
     * @minimum 1
     * @maximum 2147483647
     */
  spaceId: number;
  file: Blob | File;
};
