/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Reservae API
 * API para gerenciamento de espaços, disponibilidades e reservas.
 * OpenAPI spec version: v1
 */

export interface ResetPasswordRequest {
  /** @nullable */
  email: string | null;
  /** @nullable */
  resetCode: string | null;
  /** @nullable */
  newPassword: string | null;
}
