/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Reservae API
 * API para gerenciamento de espaços, disponibilidades e reservas.
 * OpenAPI spec version: v1
 */
import type { CategoryEnum } from './categoryEnum';

export interface SpaceDTO {
  id?: number;
  /** @nullable */
  ownerId: string | null;
  /** @nullable */
  address: string | null;
  pricePerSpot?: number;
  /** @nullable */
  title: string | null;
  /** @nullable */
  description: string | null;
  category?: CategoryEnum;
}
