/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Reservae API
 * API para gerenciamento de espaços, disponibilidades e reservas.
 * OpenAPI spec version: v1
 */
import type { SpaceDTO } from './spaceDTO';

export interface SpaceDTOPagedResponseDto {
  /** @nullable */
  items?: SpaceDTO[] | null;
  totalCount?: number;
}
