/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Reservae API
 * API para gerenciamento de espaços, disponibilidades e reservas.
 * OpenAPI spec version: v1
 */

export interface TwoFactorResponse {
  /** @nullable */
  sharedKey: string | null;
  recoveryCodesLeft: number;
  /** @nullable */
  recoveryCodes?: string[] | null;
  isTwoFactorEnabled: boolean;
  isMachineRemembered: boolean;
}
