/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Reservae API
 * API para gerenciamento de espaços, disponibilidades e reservas.
 * OpenAPI spec version: v1
 */
import type { DayOfTheWeekEnum } from './dayOfTheWeekEnum';

export interface UpdateAvailabilityRuleDTO {
  dayOfTheWeek?: DayOfTheWeekEnum;
  /** @nullable */
  startTime?: string | null;
  /** @nullable */
  endTime?: string | null;
  /** @nullable */
  validFrom?: string | null;
  /** @nullable */
  validUntil?: string | null;
  /** @nullable */
  customPricePerSpot?: number | null;
  /** @nullable */
  isActive?: boolean | null;
  /** @nullable */
  capacity?: number | null;
  /**
     * @minimum 30
     * @maximum 2147483647
     * @nullable
     */
  slotDurationMinutes?: number | null;
}
