/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Reservae API
 * API para gerenciamento de espaços, disponibilidades e reservas.
 * OpenAPI spec version: v1
 */

export interface UpdateBookableSlotDTO {
  /** @nullable */
  startsAt?: string | null;
  /** @nullable */
  endsAt?: string | null;
  /** @nullable */
  customPricePerSpot?: number | null;
  clearCustomPricePerSpot?: boolean;
  /** @nullable */
  capacity?: number | null;
  /** @nullable */
  isActive?: boolean | null;
}
