/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Reservae API
 * API para gerenciamento de espaços, disponibilidades e reservas.
 * OpenAPI spec version: v1
 */
import type { BookingStatusEnum } from './bookingStatusEnum';

export interface UpdateBookingDto {
  status?: BookingStatusEnum;
  /** @nullable */
  quantity?: number | null;
}
