/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Reservae API
 * API para gerenciamento de espaços, disponibilidades e reservas.
 * OpenAPI spec version: v1
 */
import type { CategoryEnum } from './categoryEnum';

export interface UpdateSpaceDto {
  /** @nullable */
  address?: string | null;
  /** @nullable */
  pricePerSpot?: number | null;
  /** @nullable */
  isActive?: boolean | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  description?: string | null;
  category?: CategoryEnum;
  /** @nullable */
  coverImagePath?: string | null;
}
